packages:
  - artifacts/*
  - packages/*

catalog:
  zod: ^3.23.0
  tsx: ^4.21.0
  drizzle-orm: ^0.45.1
  "@types/node": ^22.0.0

autoInstallPeers: false

onlyBuiltDependencies:
  - esbuild

overrides:
  esbuild: "0.27.3"
